(message "Starting init-orgmode.el ...")

(require 'org-habit)
(require 'org-drill)
(require 'org-mac-iCal)
(require 'org-datetree)
(require 'org-collector)
(require 'org-crypt)

;; (org-babel-do-load-languages
;;  (quote org-babel-load-languages)
;;  (quote ((emacs-lisp . t)
;;          (dot . t)
;;          (ditaa . t)
;;          (R . t)
;;          (python . t)
;;          (ruby . t)
;;          (gnuplot . t)
;;          (clojure . t)
;;          (sh . t)
;;          (ledger . t)
;;          (org . t)
;;          (calc . t)
;;          (plantuml . t)
;;          (latex . t))))

(eval-after-load "org"
  '(require 'ox-md nil t))


(org-crypt-use-before-save-magic)
(setq org-src-fontify-natively t)
(setq org-export-html-inline-images t)
(setq org-refile-use-outline-path t)
(setq org-outline-path-complete-in-steps nil)
(setq org-refile-targets '((org-agenda-files :maxlevel . 3) (nil :maxlevel . 3)))
(setq org-reverse-note-order t)
(setq org-log-into-drawer t)
(setq org-habit-following-days 7)
(setq org-habit-preceding-days 7)
(add-hook 'org-agenda-mode-hook '(lambda () (hl-line-mode 1)))
(setq org-agenda-include-diary t)
(setq org-agenda-show-all-dates t)
(setq org-agenda-repeating-timestamp-show-all t)
(setq org-deadline-warning-days 30)
(setq org-goto-interface 'outline-path-completion org-goto-max-level 10)
(setq org-export-with-timestamps nil)
(setq org-return-follows-link t)

(message "Finished init-orgmode.el")
